version: "3.8"

services:
  db:
    image: mysql:8.4.0
    container_name: studi-newsletter-db
    environment:
      - MYSQL_DATABASE=studi-db
      - MYSQL_USER= studi-user
      - MYSQL_PASSWORD=VM06Tf8OssLKvAe
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  back:
    build:
      context: ./back-newsletter
    container_name: studi-newsletter-back
    ports:
      - "8080:8080"
    depends_on:
      - db

  front:
    build:
      context: ./front-newsletter
    container_name: studi-newsletter-front
    ports:
      - "80:80"
    depends_on:
      - back

volumes:
  mysql-data:



